version: '3'
services:
  db:
    image: postgres:13-alpine
    volumes:
      - ./db:/var/lib/pgsql
    environment:
      - POSTGRES_PASSWORD=alidip97
    ports:
      - 5432:5432

  app:
    image: demo:latest
    environment:
      - PSQL_DB_USERNAME=postgres
      - PSQL_DB_PASSWORD=alidip97
      - ACTIVE_KEY=HLQgX9L7+ZGB7QZQo5s+Q89J1gyVPdGcHjnX7Mdpj9U=
      - PSQL_DB_HOST=localhost
      - PSQL_DB_PORT=5432
    depends_on:
      - db